app_cadastro_usuarios/urls.py
from django.urls import path
from . import views


app_name = 'contact'


urlpatterns = [
    path('', views.home, name='home'),
    path('users/', views.users, name='users_list'),
    path('users/<int:id>/', views.user_update, name='user_update'),
    path('users_delete/<int:id>/', views.user_delete, name='user_delete'),
]

projeto_cadastro_usuarios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_cadastro_usuarios.urls'))
]

app_cadastro_usuarios/models.py
from django.db import models


class User(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(max_length=255)
    age = models.IntegerField()

app_cadastro_usuarios/views.py
from django.shortcuts import get_object_or_404, render
from .models import User
# from django.views.decorators.http import require_http_methods


def home(request):
    return render(request, 'users/home.html')


# @require_http_methods(['GET', 'POST'])
def users(request):
    new_user = User()

    if request.method == 'POST':
        new_user.name = request.POST.get('name')
        new_user.age = request.POST.get('age')
        new_user.save()
        
    users = {
        'users': User.objects.all()
    }
    
    return render(request, 'users/users.html', users)


def user_update(request, id):
    user = get_object_or_404(User, pk=id)
    
    if request.method == 'POST':
        user.name = request.POST.get('name')
        user.age = request.POST.get('age')
        user.save()
        
        users = {
            'users': User.objects.all()
        }
        
        return render(request, 'users/users.html', users)
        
    user = {
        'user': User.objects.get(pk=id)
    }

    return render(request, 'users/user_update.html', user)


def user_delete(request, id):
    if request.method == 'POST':
        user_to_delete = get_object_or_404(User, pk=id)
        user_to_delete.delete()
        
        users = {
            'users': User.objects.all()
        }

        return render(request, 'users/users.html', users)
    
    user = {
        'user': User.objects.get(pk=id)
    }

    return render(request, 'users/user_delete.html', user)

app_cadastro_usuarios/templates/users/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="./css/style.css">

    <title>{% block 'title' %}{% endblock 'title' %}</title>
  </head>
  <body>

    <!-- As a link -->
    <nav  class="navbar navbar-light bg-info">
        <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'contact:home' %}">Cadastrar</a>
        <a class="navbar-brand" href="{% url 'contact:users_list' %}">Usuários</a>
        </div>
    </nav>
    
    <!-- As a heading -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">{% block 'heading' %}{% endblock 'heading' %}</span>
        </div>
    </nav>


    {% block content %}{% endblock content %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app_cadastro_usuarios/templates/users/home.html
{% extends 'users/base.html' %}
{% block 'title' %}Cadastro{% endblock %}
{% block 'heading' %}Cadastrar Usuário{% endblock %}
{% block content %}
<div class="container text-center my-5">
  <form action="{% url 'contact:users_list' %}" method="post">
    {% csrf_token %}
    <div class="row my-2 py-2 bg-success bg-gradient text-white rounded-3 border-info">
      <div class="col-sm">Nome:</div>
      <div class="col-sm">Idade:</div>
      <div class="col-sm">Cadastrar?</div>
    </div>

    <div class="row my-2 py-2 bg-info bg-gradient text-white rounded-3 border-primary">
      <div class="col-sm p-1 mx-1"><input class="form-control" type="text" name="name" value="{{user.name}}"></div>
      <div class="col-sm p-1 mx-1"><input class="form-control" type="text" name="age" value="{{user.age}}"></div>  
      <div class="col-sm"><input class="btn btn-success p-1 my-2" type="submit" name="delete" value="Cadastrar"></div>
    </div>
  </form>
</div>
{% endblock %}

app_cadastro_usuarios/templates/users/user_delete.html
{% extends 'users/base.html' %}
{% block 'title' %}Deletando{% endblock %}
{% block 'heading' %}Deletar um Usuário{% endblock %}
{% block content %}
<div class="container text-center my-5">
  <form action="{% url 'contact:user_delete' user.id %}" method="post">
    {% csrf_token %}
    <div class="row my-2 py-2 bg-danger bg-gradient text-white rounded-3 border-info">
      <div class="col-sm">ID:</div>
      <div class="col-sm">Nome:</div>
      <div class="col-sm">Idade:</div>
      <div class="col-sm">Deletar?</div>
    </div>

    <div class="row my-2 py-2 bg-info bg-gradient text-white rounded-3 border-primary">
      <div class="col-sm p-1">{{user.id}}</div>
      <div class="col-sm p-1">{{user.name}}</div>
      <div class="col-sm p-1">{{user.age}}</div>
      <div class="col-sm"><input class="btn btn-danger p-1" type="submit" name="delete" value="Deletar"></div>
    </div>
  </form>
</div>
{% endblock %}

app_cadastro_usuarios/templates/users/user_update.html
{% extends 'users/base.html' %}
{% block 'title' %}Atualizando{% endblock %}
{% block 'heading' %}Atualizar Usuário{% endblock %}
{% block content %}
<div class="container text-center my-5">
  <form action="{% url 'contact:user_update' user.id %}" method="post">
    {% csrf_token %}
    <div class="row my-2 py-2 bg-warning bg-gradient text-black rounded-3 border-info">
      <div class="col-sm">ID:</div>
      <div class="col-sm">Nome:</div>
      <div class="col-sm">Idade:</div>
      <div class="col-sm">Atualizar?</div>
    </div>

    <div class="row my-2 py-2 bg-info bg-gradient text-white rounded-3 border-primary">
      <div class="col-sm p-1 my-2">{{user.id}}</div>
      <div class="col-sm p-1 mx-1"><input class="form-control" type="text" name="name" value="{{user.name}}"></div>
      <div class="col-sm p-1 mx-1"><input class="form-control" type="text" name="age" value="{{user.age}}"></div>  
      <div class="col-sm"><input class="btn btn-danger p-1 my-2" type="submit" name="delete" value="Atualizar"></div>
    </div>
  </form>
</div>
{% endblock %}

app_cadastro_usuarios/templates/users/users.html
{% extends 'users/base.html' %}
{% block 'title' %}Usuários{% endblock %}
{% block 'heading' %}Lista de Usuários{% endblock %}
{% block content %}
<div class="container text-center my-5">
  <div class="row my-2 py-2 bg-primary bg-gradient text-white rounded-3 border-info">
    <div class="col-sm">ID:</div>
    <div class="col-sm">Nome:</div>
    <div class="col-sm">Idade:</div>
    <div class="col-sm"></div>
    <div class="col-sm"></div>
  </div>
  
  {% for user in users %}
    <div class="row my-2 py-2 bg-info bg-gradient text-white rounded-3 border-primary">
      <div class="col-sm p-1">{{user.id}}</div>
      <div class="col-sm p-1">{{user.name}}</div>
      <div class="col-sm p-1">{{user.age}}</div>
      <div class="col-sm"><a class="btn btn-success p-1" href="{% url 'contact:user_update' user.id %}">Atualizar</a></div>
      <div class="col-sm"><a class="btn btn-danger p-1" href="{% url 'contact:user_delete' user.id %}">Deletar</a></div>
    </div>
  {% endfor %}
</div>
{% endblock %}